Deck.create(name: "Roman Numerals")

Card.create(deck_id: 1, question: "I", answer: "1" )
Card.create(deck_id: 1, question: "II", answer: "2" )
Card.create(deck_id: 1, question: "III", answer: "3" )
Card.create(deck_id: 1, question: "IV", answer: "4" )
Card.create(deck_id: 1, question: "V", answer: "5" )
Card.create(deck_id: 1, question: "VI", answer: "6" )
Card.create(deck_id: 1, question: "VII", answer: "7" )
Card.create(deck_id: 1, question: "VIII", answer: "8" )
Card.create(deck_id: 1, question: "VIX", answer: "9" )
Card.create(deck_id: 1, question: "X", answer: "10" )
Card.create(deck_id: 1, question: "XI", answer: "11" )
Card.create(deck_id: 1, question: "XVI", answer: "16" )
Card.create(deck_id: 1, question: "XVIII", answer: "18" )
Card.create(deck_id: 1, question: "LXI", answer: "61" )
Card.create(deck_id: 1, question: "LXX", answer: "70" )
Card.create(deck_id: 1, question: "C", answer: "100" )

Deck.create(name: "State Capitals")

Card.create(deck_id: 2, question: "What is the capital of Illinois", answer: "Springfield" )
Card.create(deck_id: 2, question: "What is the capital of Missouri", answer: "Jefferson City" )
Card.create(deck_id: 2, question: "What is the capital of Indiana", answer: "Indianapolis" )
Card.create(deck_id: 2, question: "What is the capital of Ohio", answer: "Columbus" )
Card.create(deck_id: 2, question: "What is the capital of Rhode Island", answer: "Providence" )
Card.create(deck_id: 2, question: "What is the capital of New York", answer: "Albany" )
Card.create(deck_id: 2, question: "What is the capital of New Jersey", answer: "Ternton" )
Card.create(deck_id: 2, question: "What is the capital of North Carolina", answer: "Raleigh" )
Card.create(deck_id: 2, question: "What is the capital of South Carolina", answer: "Columbia" )
Card.create(deck_id: 2, question: "What is the capital of California", answer: "Sacramento" )
Card.create(deck_id: 2, question: "What is the capital of Nevada", answer: "Reno" )
Card.create(deck_id: 2, question: "What is the capital of Utah", answer: "Salt Lake City" )
Card.create(deck_id: 2, question: "What is the capital of Idaho", answer: "Boise" )
Card.create(deck_id: 2, question: "What is the capital of Montana", answer: "Helena" )
Card.create(deck_id: 2, question: "What is the capital of Wyoming", answer: "Cheyenne" )
Card.create(deck_id: 2, question: "What is the capital of Colorado", answer: "Denver" )
Card.create(deck_id: 2, question: "What is the capital of New Mexico", answer: "Santa Fe" )
Card.create(deck_id: 2, question: "What is the capital of Alabama", answer: "Montgomery" )
Card.create(deck_id: 2, question: "What is the capital of Mississippi", answer: "Jackson" )
Card.create(deck_id: 2, question: "What is the capital of Florida", answer: "Tallahassee" )
Card.create(deck_id: 2, question: "What is the capital of Georgia", answer: "Atlanta" )
Card.create(deck_id: 2, question: "What is the capital of Louisianna", answer: "Baton Rouge" )
Card.create(deck_id: 2, question: "What is the capital of Texas", answer: "Austin" )
Card.create(deck_id: 2, question: "What is the capital of Wisconsin", answer: "Madison" )
Card.create(deck_id: 2, question: "What is the capital of Minnesota", answer: "St. Paul" )
Card.create(deck_id: 2, question: "What is the capital of Michigan", answer: "Lansing" )
Card.create(deck_id: 2, question: "What is the capital of Maine", answer: "Augusta" )
Card.create(deck_id: 2, question: "What is the capital of Oregon", answer: "Salem" )
Card.create(deck_id: 2, question: "What is the capital of Washington", answer: "Olympia" )
Card.create(deck_id: 2, question: "What is the capital of Kansas", answer: "Topeka" )
Card.create(deck_id: 2, question: "What is the capital of Nebraska", answer: "Lincoln" )
Card.create(deck_id: 2, question: "What is the capital of South Dakota", answer: "Pierre" )
Card.create(deck_id: 2, question: "What is the capital of North Dakota", answer: "Bismarck" )
Card.create(deck_id: 2, question: "What is the capital of Minnesota", answer: "St. Paul" )
Card.create(deck_id: 2, question: "What is the capital of Vermont", answer: "Montpelier" )
Card.create(deck_id: 2, question: "What is the capital of New Hampshire", answer: "Concord" )
Card.create(deck_id: 2, question: "What is the capital of Connecticut", answer: "Hartford" )
Card.create(deck_id: 2, question: "What is the capital of Virginia", answer: "Richmond" )
Card.create(deck_id: 2, question: "What is the capital of Kentucky", answer: "Frankfurt" )
Card.create(deck_id: 2, question: "What is the capital of Tennessee", answer: "Nashville" )
Card.create(deck_id: 2, question: "What is the capital of Arkansas", answer: "Little Rock" )
Card.create(deck_id: 2, question: "What is the capital of Alaska", answer: "Juneau" )
Card.create(deck_id: 2, question: "What is the capital of Hawaii", answer: "Honolulu" )
Card.create(deck_id: 2, question: "What is the capital of Maryland", answer: "Annapolis" )
Card.create(deck_id: 2, question: "What is the capital of Deleware", answer: "Dover" )
Card.create(deck_id: 2, question: "What is the capital of Oklahoma ", answer: "Oklahoma City" )
Card.create(deck_id: 2, question: "What is the capital of Pennsylvania", answer: "Harrisburg" )
Card.create(deck_id: 2, question: "What is the capital of Arizona", answer: "Phoenix" )
Card.create(deck_id: 2, question: "What is the capital of Massachusetts", answer: "Boston" )
Card.create(deck_id: 2, question: "What is the capital of Iowa", answer: "Des Moines" )

Deck.create(name: "Presidents")

Card.create(deck_id: 3, question: "First President", answer: "George Washington" )
Card.create(deck_id: 3, question: "Civil War President", answer: "Abraham Lincoln" )
Card.create(deck_id: 3, question: "First President to Die in Office", answer: "William Henry Harrison" )
Card.create(deck_id: 3, question: "WWI President", answer: "Woodrow Wilson" )
Card.create(deck_id: 3, question: "Elected to Four Terms", answer: "Franklin Roosevelt" )
Card.create(deck_id: 3, question: "President who Resigned", answer: "Richard Nixon" )
Card.create(deck_id: 3, question: "President who was never elected as Pres or VP", answer: "Gerald Ford" )
Card.create(deck_id: 3, question: "President Elected to two terms not in a row", answer: "Grover Clevland" )

User.create(username: "walrus", password: "a");

10.times do
	User.create(username: Faker::Name.name, password: User.encrypt)
end

